services:
  web:
    build: .
    container_name: skynet_backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: skynet_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
